{% set name = "flwr" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flwr-{{ version }}.tar.gz
  sha256: acc0ea535c3b47fc4297837650b4da22ff5f95001f374835605f38597172f6bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flwr = flwr.cli.app:app
    - flower-superexec = flwr.superexec.app:run_superexec
    - flower-simulation = flwr.simulation.run_simulation:run_simulation_from_cli
    - flower-superlink = flwr.server.app:run_superlink
    - flower-supernode = flwr.client.supernode.app:run_supernode
    - flower-server-app = flwr.server.run_serverapp:run_server_app
    - flwr-clientapp = flwr.client.clientapp:flwr_clientapp
    - flower-client-app = flwr.client.supernode:run_client_app

requirements:
  host:
    - pip
    - poetry-core >=1.4.0
    - python {{ python_min }}
  run:
    # There is some snafu with grpcio version availability on Conda, removing some pinning and hoping for the best...
    # Upstream also using some unconventional Protobuf version numbers...
    - python >={{ python_min }}
    - numpy >=1.26.0,<3.0.0
    - grpcio >=1.60.0,<2.0.0,!=1.64.2,<=1.64.3
    - protobuf # >=4.25.2,<5.0.0
    - cryptography >=42.0.4,<43.0.0
    - pycryptodome >=3.18.0,<4.0.0
    - iterators >=0.0.2,<0.0.3
    - typer >=0.12.5,<0.13.0
    - tomli >=2.0.1,<3.0.0
    - tomli-w >=1.0.0,<2.0.0
    - pathspec >=0.12.1,<0.13.0
    - hatchling >=1.25.0,<2.0.0
    - rich >=13.5.0,<14.0.0

test:
  imports:
    - flwr
  commands:
    # Remove pip check see above
    # - pip check
    - flwr --help
    - flower-superlink --help
    # Skip running superexec as it generates an INFO log
    # - flower-superexec --help
    - flower-supernode --help
    - flower-client-app --help
    - flower-server-app --help
    - flower-simulation --help
    - flwr-clientapp --help
  requires:
    - pip
    - ray-core
    - python {{ python_min }}

about:
  home: https://flower.ai
  doc_url: https://flower.ai/docs/
  dev_url: https://github.com/adap/flower
  summary: Flower - A Friendly Federated Learning Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tanertopal
    - danieljanes
    - flwrmachine
    - thewchan
