{% set name = "flwr" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flwr-{{ version }}.tar.gz
  sha256: a251a9532ccc9617efc616f2ae404534e51d580396ef0aa023a51668f752d969

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - flower-client = flwr.client:run_client
    - flower-driver-api = flwr.server:run_driver_api
    - flower-fleet-api = flwr.server:run_fleet_api
    - flower-server = flwr.server:run_server

requirements:
  host:
    - pip
    - poetry-core >=1.4.0
    - python >=3.7,<4.0
  run:
    # There is some snafu with grpcio version availability on Conda, removing some pinning and hoping for the best...
    - python >=3.7,<4.0
    - grpcio >1.49.1 #>=1.48.2  # ,<2.0.0,!=1.52.0
    - iterators >=0.0.2,<0.0.3
    - numpy # >=1.21.0,<2.0.0
    - protobuf # >=3.19.0,<4.0.0
    - importlib-metadata >=4.0.0,<5.0.0

test:
  imports:
    - flwr
  commands:
    # Remove pip check see above
    # - pip check
    - flower-client --help
    - flower-driver-api --help
    - flower-fleet-api --help
    - flower-server --help
  requires:
    - pip

about:
  home: https://flower.dev
  doc_url: https://flower.dev/docs/
  dev_url: https://github.com/adap/flower
  summary: Flower - A Friendly Federated Learning Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
