{% set name = "flwr" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flwr-{{ version }}.tar.gz
  sha256: f0f2428867f577d1750d47b8d9a66215bb6cb67326abf2b8e300416b4219da83

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flwr = flwr.cli.app:app
    - flwr-simulation = flwr.simulation.app:flwr_simulation
    - flower-simulation = flwr.simulation.run_simulation:run_simulation_from_cli
    - flower-superlink = flwr.server.app:run_superlink
    - flower-supernode = flwr.client.supernode.app:run_supernode
    - flwr-server-app = flwr.server.serverapp:flwr_serverapp
    - flwr-clientapp = flwr.client.clientapp:flwr_clientapp

requirements:
  host:
    - pip
    - poetry-core >=1.4.0
    - python {{ python_min }}
  run:
    # There is some snafu with grpcio version availability on Conda, removing some pinning and hoping for the best...
    # Upstream also using some unconventional Protobuf version numbers...
    - python >={{ python_min }}
    - numpy >=1.26.0,<3.0.0
    - grpcio >=1.62.3,<2.0.0,!=1.65.0
    - protobuf # >=4.21.6,<5.0.0
    - cryptography >=44.0.1,<45.0.0
    - pycryptodome >=3.18.0,<4.0.0
    - iterators >=0.0.2,<0.0.3
    - typer >=0.12.5,<0.13.0
    - tomli >=2.0.1,<3.0.0
    - tomli-w >=1.0.0,<2.0.0
    - pathspec >=0.12.1,<0.13.0
    - rich >=13.5.0,<14.0.0
    - typing_extensions
    - pyyaml >=6.0.2,<7.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - flwr
  commands:
    # Remove pip check see above
    # - pip check
    - flwr --help
    - flower-simulation --help
    - flwr-simulation --help
    - flower-superlink --help
    - flower-supernode --help
    - flwr-server-app --help
    - flwr-clientapp --help
  requires:
    - pip
    - ray-core
    - python {{ python_min }}

about:
  home: https://flower.ai
  doc_url: https://flower.ai/docs/
  dev_url: https://github.com/adap/flower
  summary: Flower - A Friendly Federated Learning Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tanertopal
    - danieljanes
    - flwrmachine
    - thewchan
