schema_version: 1

context:
  name: flwr
  version: 1.19.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/flwr-${{ version }}.tar.gz
  sha256: cda27dce6f1c350353f6179aaf949e3d154e25eaeec76ed78c8844c4d7be0bf5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - flwr = flwr.cli.app:app
      - flwr-simulation = flwr.simulation.app:flwr_simulation
      - flower-simulation = flwr.simulation.run_simulation:run_simulation_from_cli
      - flower-superlink = flwr.server.app:run_superlink
      - flower-supernode = flwr.supernode.cli:flower_supernode
      - flwr-server-app = flwr.server.serverapp:flwr_serverapp
      - flwr-clientapp = flwr.supernode.cli:flwr_clientapp

requirements:
  host:
    - pip
    - poetry-core >=2.1.3
    - python ${{ python_min }}.*
  run:
    # There is some snafu with grpcio version availability on Conda, removing some pinning and hoping for the best...
    # Upstream also using some unconventional Protobuf version numbers...
    - python >=${{ python_min }}
    - numpy >=1.26.0,<3.0.0
    - grpcio >=1.62.3,<2.0.0,!=1.65.0
    - protobuf  # >=4.21.6,<5.0.0
    - cryptography >=44.0.1,<45.0.0
    - pycryptodome >=3.18.0,<4.0.0
    - iterators >=0.0.2,<0.0.3
    - typer >=0.12.5,<0.13.0
    - tomli >=2.0.1,<3.0.0
    - tomli-w >=1.0.0,<2.0.0
    - pathspec >=0.12.1,<0.13.0
    - rich >=13.5.0,<14.0.0
    - pyyaml >=6.0.2,<7.0.0
    - requests >=2.31.0,<3.0.0
    - click <8.2.0

tests:
  - python:
      imports:
        - flwr
      # Disable pip check for now, see above
      pip_check: false
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - ray-core
        - python ${{ python_min }}.*
    script:
      - flwr --help
      - flower-simulation --help
      - flwr-simulation --help
      - flower-superlink --help
      - flower-supernode --help
      - flwr-server-app --help
      - flwr-clientapp --help

about:
  summary: Flower - A Friendly Federated Learning Framework
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://flower.ai
  repository: https://github.com/adap/flower
  documentation: https://flower.ai/docs/

extra:
  recipe-maintainers:
    - tanertopal
    - danieljanes
    - flwrmachine
    - thewchan
